model_params:
  model: Net


args:
  expdir: "."
  logdir: "log"

stages:

  data_params:
    batch_size: 32
    num_workers: 0

  state_params:
    num_epochs: 1
    main_metric: &reduce_metric accuracy01
    minimize_metric: False

  criterion_params:
    criterion: CrossEntropyLoss

  scheduler_params:
    scheduler: MultiStepLR
    milestones: [10]
    gamma: 0.3

  callbacks_params:
    loss:
      callback: CriterionCallback
    optimizer:
      callback: OptimizerCallback
    accuracy:
      callback: AccuracyCallback
      accuracy_args: [1]
    scheduler:
      callback: SchedulerCallback
      reduced_metric: *reduce_metric
    saver:
      callback: CheckpointCallback

  stage1:

    optimizer_params:
      optimizer: Adam
      lr: 0.001
      weight_decay: 0.0001