extend: base_time

layout:
  - type: panel
    title: main
    parent_cols: 1
    row_height: 300
    items:
      - type: table
        source: [loss]
        cols: 1
      - type: series
        source: _other